module RuboCop
  module Cop
    module Grep
      class Grepx < ::RuboCop::Cop::Base
        include RangeHelp

        type rule = {
          'Pattern' => String | Array[String],
          'Message' => String,
          'MatchInComment' => bool?,

          # Regexp options
          'Multiline' => bool?,
          'Extended' => bool?,
          'Ignorecase' => bool?,
        }

        type config = {
          'Rules' => Array[rule]
        }

        def on_new_investigation: () -> void

        private def position_from_matchdata: (MatchData) -> {
          line: Integer,
          column: Integer,
          length: Integer,
        }

        private def in_comment?: (MatchData) -> bool

        private def regexp_option: (rule) -> Integer

        def cop_config: () -> config
      end
      # HACK: Steep has a bug when the class name is the same as the parent namespace name.
      class Grep = Grepx
    end
  end
end
