module RuboCop
  module Cop
    module Grep
      class Grepx < ::RuboCop::Cop::Base
        include RangeHelp

        type config = {
          'Rules' => Array[{
            'Pattern' => String | Array[String],
            'Message' => String,
            'MatchInComment' => bool?,
          }]
        }

        def on_new_investigation: () -> void

        private def position_from_matchdata: (MatchData) -> {
          line: Integer,
          column: Integer,
          length: Integer,
        }

        private def in_comment?: (MatchData) -> bool

        def cop_config: () -> config
      end
      # HACK: Steep has a bug when the class name is the same as the parent namespace name.
      class Grep = Grepx
    end
  end
end
